### ISSUE TITLE
Retrieving Books

### ISSUE THREAD

**Issue by carter7k** [CMPUT301F20T14/BookBox#25]
Books need to store their ID as well, so that we can access the book in firebase (they have a random doc id so there can be multiple of the same book)

**Comment by carter7k** [comment]
See branch Carter-constants

**Comment by olivier-vadiaval** [comment]
ISBN can be used as id
They're unique like the username
Since we'll need to check if a book being added is already in the collection, I thought it would be better to have the isbn as key like for username for the users.

**Comment by olivier-vadiaval** [comment]
> See branch Carter-constants

Can't seem to find that branch

**Comment by carter7k** [comment]
Oh, I added it to Olivier-db.
The isbn is only good if there is 1 of each book, but several users could have the same book (same edition/variation) and they would all have the same isbn, which is why they should have a separate id (we can just let firebase auto-id the books)

**Comment by olivier-vadiaval** [comment]
Oh right, makes sense now. I didn't think about that. Thanks

**Comment by carter7k** [comment]
What commit did you change it in? We can just revert it.

**Comment by olivier-vadiaval** [comment]
I think i made some other changes with that commit too. If we revert it,
might lose those as other changes too. No worries. I’ll fix it. I’m about
with the add functionality
