### ISSUE TITLE
Incorrect ISBN's

### ISSUE THREAD

**Issue by carter7k** [CMPUT301F20T14/BookBox#32]
This is (for now) a pretty minor issue, but you can enter any sequence of numbers and it will be treated like an isbn.
When we get around to fixing this we should also find out how to treat 10 digit isbn's. Keep them as is, or convert to isbn-13.
We should also verify that the isbn's are valid. https://en.wikipedia.org/wiki/International_Standard_Book_Number#Check_digits

**Comment by olivier-vadiaval** [comment]
I'll fix that
